---
- name: Install kubectl using snap
  ansible.builtin.shell: |
    snap install kubectl --classic
  args:
    creates: /snap/bin/kubectl

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client
  register: kubectl_out
  changed_when: false

- name: Show kubectl version
  ansible.builtin.debug:
    msg: "{{ kubectl_out.stdout }}"

- name: Check if Minikube is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/minikube
  register: minikube_bin

- name: Download Minikube binary
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
  when: not minikube_bin.stat.exists

- name: Start Minikube with Docker drive
  become: false
  ansible.builtin.shell: |
    minikube start --driver=docker
  register: minikube_start
  changed_when: true
  failed_when: "'Exiting' in minikube_start.stdout or 'Exiting' in minikube_start.stderr"

- name: Verify Minikube status
  ansible.builtin.command: minikube status
  register: minikube_status
  changed_when: false

- name: Display Minikube status
  ansible.builtin.debug:
    msg: "{{ minikube_status.stdout }}"
