---
- name: Install kubectl using snap
  become: yes
  community.general.snap:
    name: kubectl
    classic: yes
    state: present

- name: Verify kubectl installation
  ansible.builtin.command: kubectl version --client
  register: kubectl_out
  changed_when: false

- name: Show kubectl version
  ansible.builtin.debug:
    msg: "{{ kubectl_out.stdout }}"

- name: Check if Minikube is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/minikube
  register: minikube_bin

- name: Download Minikube binary
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'

- name: Check Minikube status
  become: false
  ansible.builtin.command: minikube status --format='{{ "{{.Host}}" }}'
  register: minikube_status
  changed_when: false

- name: Start Minikube with Docker driver
  become: false
  ansible.builtin.shell: |
    minikube start --driver=docker
  register: minikube_start
  when: minikube_status.stdout != "Running"
  changed_when: "'Done' in minikube_start.stdout"
  failed_when:
    - "'Exiting' in minikube_start.stderr"
    - "'FAILED' in minikube_start.stderr"

- name: Display Minikube final status
  become: false
  ansible.builtin.command: minikube status
  register: minikube_final
  changed_when: false

- name: Output Minikube status
  ansible.builtin.debug:
    msg: "{{ minikube_final.stdout }}"

