$ANSIBLE_VAULT;1.1;AES256
63323534626630646536353264336565646636623738316362613236386134616364636439303131
6134613335353964633934636162343932363531316535630a393966313061373634343639393930
30323131383835336165626664376139393536396466613765653766393463626339656634656637
3633653931316262330a663666656165303163383738663233376138643466386435313731383962
38373033393831393463663532323936633462313439643030666539303662383936
